name: the pickle jar
favicon: null
layout_spectrum: 0.12848750595003366
typography_spectrum: 0.5722031064797193
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6089846703689545
  lightness: 0.03565565915778279
  saturation: 0.8384542206767946
  rhythmicContrast: 0.08194326073862612
purpose: []
