name: the pickle jar
favicon: null
layout_spectrum: 0.5597
typography_spectrum: 0.5722031064797193
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e2e2e2'
    - '#343434'
    - '#5c5c5c'
    - '#a5a5a5'
    - '#7b7b7b'
  brandStrength: 0.6089846703689545
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.08194326073862612
purpose: []
